version: '3.2'
services:
  web:
    build: ./docker/
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    working_dir: /app/app
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    hostname: db
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
  
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    environment:
        PMA_HOST: db
        PMA_USER: "root"
        PMA_PASSWORD: "password"
    restart: always
    ports:
        - "8080:80"